[mypy]
exclude = ^tests/.*\.py

[mypy-nox.*,django.*]  
ignore_missing_imports = True

[mypy-customer_portal.*]
ignore_missing_imports = True

[mypy-opensearch_dsl.*]
ignore_missing_imports = True

[mypy-kafka.*]
ignore_missing_imports = True

[mypy-html_sanitizer.*]
ignore_missing_imports = True

[mypy-msal.*]
ignore_missing_imports = True

[mypy-kq.*]
ignore_missing_imports = True

[mypy-openmock.*]
ignore_missing_imports = True

[mypy-mitreattack.stix20.*]
ignore_missing_imports = True

[mypy-the_project.migrations.*]  
ignore_errors = True

[mypy-customer_portal.api.*.schemas]
disable_error_code = valid-type

[mypy-customer_portal.api.service]
ignore_errors = True