"""Book metadata population for all 66 biblical books."""

import json
import logging
import sqlite3
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Curated metadata for all 66 books of the Protestant canon.
# Sources: standard biblical scholarship (introductory level).
BOOK_METADATA: List[Dict[str, Any]] = [
    # --- Torah / Pentateuch ---
    {
        "book_id": 1,
        "primary_genre": "narrative",
        "secondary_genres": ["law", "poetry", "genealogy"],
        "author_traditional": "Moses",
        "date_range_start": -1450,
        "date_range_end": -1400,
        "original_audience": "Israel after the Exodus",
        "original_language": "hebrew",
        "literary_features": ["chiasmus", "parallelism", "inclusio", "typology"],
        "reading_context": "Origins of the world, humanity, and God's covenant people",
        "canonical_section": "Torah",
    },
    {
        "book_id": 2,
        "primary_genre": "narrative",
        "secondary_genres": ["law", "poetry"],
        "author_traditional": "Moses",
        "date_range_start": -1450,
        "date_range_end": -1400,
        "original_audience": "Israel after the Exodus",
        "original_language": "hebrew",
        "literary_features": ["song", "theophany", "covenant formula"],
        "reading_context": "Deliverance from Egypt and covenant at Sinai",
        "canonical_section": "Torah",
    },
    {
        "book_id": 3,
        "primary_genre": "law",
        "secondary_genres": ["ritual", "narrative"],
        "author_traditional": "Moses",
        "date_range_start": -1450,
        "date_range_end": -1400,
        "original_audience": "Levitical priests and Israel",
        "original_language": "hebrew",
        "literary_features": ["repetition", "chiasmus", "ritual formula"],
        "reading_context": "Holiness code and sacrificial system",
        "canonical_section": "Torah",
    },
    {
        "book_id": 4,
        "primary_genre": "narrative",
        "secondary_genres": ["law", "census", "poetry"],
        "author_traditional": "Moses",
        "date_range_start": -1450,
        "date_range_end": -1400,
        "original_audience": "Israel in the wilderness",
        "original_language": "hebrew",
        "literary_features": ["travel narrative", "census lists", "oracle poetry"],
        "reading_context": "Wilderness wanderings between Sinai and Canaan",
        "canonical_section": "Torah",
    },
    {
        "book_id": 5,
        "primary_genre": "law",
        "secondary_genres": ["sermon", "poetry", "narrative"],
        "author_traditional": "Moses",
        "date_range_start": -1450,
        "date_range_end": -1400,
        "original_audience": "Second generation of Israel before entering Canaan",
        "original_language": "hebrew",
        "literary_features": ["covenant renewal", "blessing and curse", "song"],
        "reading_context": "Moses' farewell speeches restating the law",
        "canonical_section": "Torah",
    },
    # --- Historical Books ---
    {
        "book_id": 6,
        "primary_genre": "narrative",
        "secondary_genres": ["military", "covenant"],
        "author_traditional": "Joshua",
        "date_range_start": -1400,
        "date_range_end": -1350,
        "original_audience": "Israel settling in Canaan",
        "original_language": "hebrew",
        "literary_features": ["conquest narrative", "boundary lists", "covenant renewal"],
        "reading_context": "Conquest and settlement of the Promised Land",
        "canonical_section": "Former Prophets",
    },
    {
        "book_id": 7,
        "primary_genre": "narrative",
        "secondary_genres": ["military", "poetry"],
        "author_traditional": "Samuel",
        "date_range_start": -1050,
        "date_range_end": -1000,
        "original_audience": "Israel during the period of the judges",
        "original_language": "hebrew",
        "literary_features": ["cyclical pattern", "irony", "song"],
        "reading_context": "Cycle of sin, oppression, and deliverance before the monarchy",
        "canonical_section": "Former Prophets",
    },
    {
        "book_id": 8,
        "primary_genre": "narrative",
        "secondary_genres": ["romance", "legal"],
        "author_traditional": "Samuel",
        "date_range_start": -1050,
        "date_range_end": -1000,
        "original_audience": "Israel",
        "original_language": "hebrew",
        "literary_features": ["chiasmus", "inclusio", "wordplay"],
        "reading_context": "Loyalty and redemption during the judges period",
        "canonical_section": "Writings",
    },
    {
        "book_id": 9,
        "primary_genre": "narrative",
        "secondary_genres": ["prophecy", "poetry"],
        "author_traditional": "Samuel",
        "date_range_start": -1050,
        "date_range_end": -930,
        "original_audience": "Israel transitioning to monarchy",
        "original_language": "hebrew",
        "literary_features": ["contrast narrative", "song", "lament"],
        "reading_context": "Establishment of the monarchy under Saul and David",
        "canonical_section": "Former Prophets",
    },
    {
        "book_id": 10,
        "primary_genre": "narrative",
        "secondary_genres": ["court history", "poetry"],
        "author_traditional": "Samuel/Nathan/Gad",
        "date_range_start": -1000,
        "date_range_end": -930,
        "original_audience": "Israel under David's reign",
        "original_language": "hebrew",
        "literary_features": ["succession narrative", "lament", "chiasmus"],
        "reading_context": "David's reign, covenant, and struggles",
        "canonical_section": "Former Prophets",
    },
    {
        "book_id": 11,
        "primary_genre": "narrative",
        "secondary_genres": ["prophecy"],
        "author_traditional": "Jeremiah",
        "date_range_start": -560,
        "date_range_end": -540,
        "original_audience": "Judah in exile",
        "original_language": "hebrew",
        "literary_features": ["prophetic narrative", "regnal formula"],
        "reading_context": "Solomon's reign through the divided kingdom",
        "canonical_section": "Former Prophets",
    },
    {
        "book_id": 12,
        "primary_genre": "narrative",
        "secondary_genres": ["prophecy"],
        "author_traditional": "Jeremiah",
        "date_range_start": -560,
        "date_range_end": -540,
        "original_audience": "Judah in exile",
        "original_language": "hebrew",
        "literary_features": ["prophetic narrative", "regnal formula", "miracle stories"],
        "reading_context": "Decline of the divided kingdoms to exile",
        "canonical_section": "Former Prophets",
    },
    {
        "book_id": 13,
        "primary_genre": "narrative",
        "secondary_genres": ["genealogy", "liturgy"],
        "author_traditional": "Ezra",
        "date_range_start": -450,
        "date_range_end": -400,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["genealogy", "temple focus", "liturgical sections"],
        "reading_context": "Israel's history from Adam to David (priestly perspective)",
        "canonical_section": "Writings",
    },
    {
        "book_id": 14,
        "primary_genre": "narrative",
        "secondary_genres": ["genealogy", "liturgy"],
        "author_traditional": "Ezra",
        "date_range_start": -450,
        "date_range_end": -400,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["temple focus", "sermon", "prayer"],
        "reading_context": "Solomon through the exile (priestly perspective)",
        "canonical_section": "Writings",
    },
    {
        "book_id": 15,
        "primary_genre": "narrative",
        "secondary_genres": ["memoir", "decree"],
        "author_traditional": "Ezra",
        "date_range_start": -450,
        "date_range_end": -400,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["first-person narrative", "official documents", "prayer"],
        "reading_context": "Return from exile and rebuilding of the temple",
        "canonical_section": "Writings",
    },
    {
        "book_id": 16,
        "primary_genre": "narrative",
        "secondary_genres": ["memoir", "prayer"],
        "author_traditional": "Nehemiah",
        "date_range_start": -430,
        "date_range_end": -400,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["first-person narrative", "lists", "prayer"],
        "reading_context": "Rebuilding Jerusalem's walls and renewing the covenant",
        "canonical_section": "Writings",
    },
    {
        "book_id": 17,
        "primary_genre": "narrative",
        "secondary_genres": ["court tale", "comedy"],
        "author_traditional": "Mordecai",
        "date_range_start": -460,
        "date_range_end": -400,
        "original_audience": "Persian-era diaspora Jews",
        "original_language": "hebrew",
        "literary_features": ["irony", "reversal", "chiasmus", "banquet scenes"],
        "reading_context": "Divine providence protecting Jews in Persian exile",
        "canonical_section": "Writings",
    },
    # --- Wisdom / Poetry ---
    {
        "book_id": 18,
        "primary_genre": "wisdom",
        "secondary_genres": ["poetry", "dialogue", "lament"],
        "author_traditional": "Job/Moses",
        "date_range_start": -2000,
        "date_range_end": -500,
        "original_audience": "Wisdom seekers",
        "original_language": "hebrew",
        "literary_features": ["dialogue", "chiasmus", "irony", "theophany", "inclusio"],
        "reading_context": "Suffering of the righteous and the limits of human wisdom",
        "canonical_section": "Writings",
    },
    {
        "book_id": 19,
        "primary_genre": "poetry",
        "secondary_genres": ["hymn", "lament", "wisdom", "royal", "thanksgiving"],
        "author_traditional": "David and others",
        "date_range_start": -1000,
        "date_range_end": -400,
        "original_audience": "Israel's worshipping community",
        "original_language": "hebrew",
        "literary_features": ["parallelism", "acrostic", "chiasmus", "inclusio", "selah"],
        "reading_context": "Prayer book and hymnal of ancient Israel",
        "canonical_section": "Writings",
    },
    {
        "book_id": 20,
        "primary_genre": "wisdom",
        "secondary_genres": ["poetry", "instruction"],
        "author_traditional": "Solomon and others",
        "date_range_start": -970,
        "date_range_end": -700,
        "original_audience": "Young men and wisdom seekers",
        "original_language": "hebrew",
        "literary_features": ["parallelism", "acrostic", "personification", "numerical sayings"],
        "reading_context": "Practical wisdom for daily living",
        "canonical_section": "Writings",
    },
    {
        "book_id": 21,
        "primary_genre": "wisdom",
        "secondary_genres": ["philosophy", "poetry"],
        "author_traditional": "Solomon",
        "date_range_start": -970,
        "date_range_end": -450,
        "original_audience": "Wisdom seekers",
        "original_language": "hebrew",
        "literary_features": ["refrain", "inclusio", "irony"],
        "reading_context": "Reflection on meaning, purpose, and the human condition",
        "canonical_section": "Writings",
    },
    {
        "book_id": 22,
        "primary_genre": "poetry",
        "secondary_genres": ["love song", "allegory"],
        "author_traditional": "Solomon",
        "date_range_start": -970,
        "date_range_end": -900,
        "original_audience": "Israel",
        "original_language": "hebrew",
        "literary_features": ["dialogue", "imagery", "chiasmus", "refrain"],
        "reading_context": "Celebration of love between bride and bridegroom",
        "canonical_section": "Writings",
    },
    # --- Major Prophets ---
    {
        "book_id": 23,
        "primary_genre": "prophecy",
        "secondary_genres": ["poetry", "narrative", "apocalyptic"],
        "author_traditional": "Isaiah",
        "date_range_start": -740,
        "date_range_end": -680,
        "original_audience": "Judah and Jerusalem",
        "original_language": "hebrew",
        "literary_features": ["parallelism", "inclusio", "servant songs", "chiasmus"],
        "reading_context": "Judgment and hope during Assyrian crisis",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 24,
        "primary_genre": "prophecy",
        "secondary_genres": ["poetry", "narrative", "lament"],
        "author_traditional": "Jeremiah",
        "date_range_start": -626,
        "date_range_end": -586,
        "original_audience": "Judah before and during the Babylonian exile",
        "original_language": "hebrew",
        "literary_features": ["confessions", "symbolic actions", "lament"],
        "reading_context": "Warning of judgment and promise of new covenant",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 25,
        "primary_genre": "poetry",
        "secondary_genres": ["lament"],
        "author_traditional": "Jeremiah",
        "date_range_start": -586,
        "date_range_end": -580,
        "original_audience": "Survivors of Jerusalem's destruction",
        "original_language": "hebrew",
        "literary_features": ["acrostic", "qinah meter", "chiasmus"],
        "reading_context": "Mourning the destruction of Jerusalem and the temple",
        "canonical_section": "Writings",
    },
    {
        "book_id": 26,
        "primary_genre": "prophecy",
        "secondary_genres": ["apocalyptic", "vision", "poetry"],
        "author_traditional": "Ezekiel",
        "date_range_start": -593,
        "date_range_end": -571,
        "original_audience": "Jewish exiles in Babylon",
        "original_language": "hebrew",
        "literary_features": ["vision", "symbolic action", "allegory", "chiasmus"],
        "reading_context": "Judgment on Israel and nations, and future restoration",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 27,
        "primary_genre": "apocalyptic",
        "secondary_genres": ["narrative", "prophecy", "vision"],
        "author_traditional": "Daniel",
        "date_range_start": -605,
        "date_range_end": -530,
        "original_audience": "Jews in Babylonian/Persian exile",
        "original_language": "hebrew",
        "literary_features": ["chiasmus", "court tale", "vision", "symbolic numbers"],
        "reading_context": "Faithfulness in exile and God's sovereignty over empires",
        "canonical_section": "Writings",
    },
    # --- Minor Prophets ---
    {
        "book_id": 28,
        "primary_genre": "prophecy",
        "secondary_genres": ["allegory", "poetry"],
        "author_traditional": "Hosea",
        "date_range_start": -750,
        "date_range_end": -715,
        "original_audience": "Northern kingdom of Israel",
        "original_language": "hebrew",
        "literary_features": ["marriage metaphor", "wordplay", "covenant lawsuit"],
        "reading_context": "God's faithful love despite Israel's spiritual adultery",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 29,
        "primary_genre": "prophecy",
        "secondary_genres": ["apocalyptic", "poetry"],
        "author_traditional": "Joel",
        "date_range_start": -835,
        "date_range_end": -400,
        "original_audience": "Judah",
        "original_language": "hebrew",
        "literary_features": ["locust imagery", "day of the Lord", "chiasmus"],
        "reading_context": "Locust plague as metaphor for divine judgment and restoration",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 30,
        "primary_genre": "prophecy",
        "secondary_genres": ["social justice", "poetry"],
        "author_traditional": "Amos",
        "date_range_start": -760,
        "date_range_end": -750,
        "original_audience": "Northern kingdom of Israel",
        "original_language": "hebrew",
        "literary_features": ["oracles against nations", "visions", "doxology", "wordplay"],
        "reading_context": "Social justice and judgment on Israel's complacency",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 31,
        "primary_genre": "prophecy",
        "secondary_genres": ["oracle"],
        "author_traditional": "Obadiah",
        "date_range_start": -586,
        "date_range_end": -550,
        "original_audience": "Judah",
        "original_language": "hebrew",
        "literary_features": ["chiasmus", "day of the Lord"],
        "reading_context": "Judgment on Edom for betraying Judah",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 32,
        "primary_genre": "narrative",
        "secondary_genres": ["prophecy", "satire"],
        "author_traditional": "Jonah",
        "date_range_start": -780,
        "date_range_end": -750,
        "original_audience": "Israel",
        "original_language": "hebrew",
        "literary_features": ["irony", "chiasmus", "prayer/psalm", "reversal"],
        "reading_context": "God's compassion extending beyond Israel to the nations",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 33,
        "primary_genre": "prophecy",
        "secondary_genres": ["poetry", "lawsuit"],
        "author_traditional": "Micah",
        "date_range_start": -735,
        "date_range_end": -700,
        "original_audience": "Judah and Samaria",
        "original_language": "hebrew",
        "literary_features": ["covenant lawsuit", "wordplay", "chiasmus"],
        "reading_context": "Justice, mercy, and messianic hope amid social corruption",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 34,
        "primary_genre": "prophecy",
        "secondary_genres": ["poetry", "oracle"],
        "author_traditional": "Nahum",
        "date_range_start": -660,
        "date_range_end": -612,
        "original_audience": "Judah",
        "original_language": "hebrew",
        "literary_features": ["acrostic", "theophany", "vivid imagery"],
        "reading_context": "God's judgment against Nineveh and comfort for Judah",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 35,
        "primary_genre": "prophecy",
        "secondary_genres": ["dialogue", "poetry"],
        "author_traditional": "Habakkuk",
        "date_range_start": -610,
        "date_range_end": -600,
        "original_audience": "Judah",
        "original_language": "hebrew",
        "literary_features": ["dialogue with God", "woe oracles", "psalm/theophany"],
        "reading_context": "Wrestling with divine justice amid Babylonian threat",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 36,
        "primary_genre": "prophecy",
        "secondary_genres": ["oracle", "poetry"],
        "author_traditional": "Zephaniah",
        "date_range_start": -640,
        "date_range_end": -625,
        "original_audience": "Judah before Josiah's reforms",
        "original_language": "hebrew",
        "literary_features": ["day of the Lord", "oracles against nations", "chiasmus"],
        "reading_context": "Cosmic judgment and promise of a purified remnant",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 37,
        "primary_genre": "prophecy",
        "secondary_genres": ["exhortation"],
        "author_traditional": "Haggai",
        "date_range_start": -520,
        "date_range_end": -520,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["dated oracles", "rhetorical questions"],
        "reading_context": "Call to rebuild the temple after return from exile",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 38,
        "primary_genre": "prophecy",
        "secondary_genres": ["apocalyptic", "vision"],
        "author_traditional": "Zechariah",
        "date_range_start": -520,
        "date_range_end": -480,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["night visions", "symbolic imagery", "messianic oracle"],
        "reading_context": "Visions of restoration, messianic hope, and the coming kingdom",
        "canonical_section": "Latter Prophets",
    },
    {
        "book_id": 39,
        "primary_genre": "prophecy",
        "secondary_genres": ["disputation"],
        "author_traditional": "Malachi",
        "date_range_start": -460,
        "date_range_end": -430,
        "original_audience": "Post-exilic Judah",
        "original_language": "hebrew",
        "literary_features": ["disputation dialogue", "rhetorical questions"],
        "reading_context": "Covenant faithfulness and the coming day of the Lord",
        "canonical_section": "Latter Prophets",
    },
    # --- New Testament: Gospels ---
    {
        "book_id": 40,
        "primary_genre": "gospel",
        "secondary_genres": ["narrative", "discourse", "genealogy"],
        "author_traditional": "Matthew",
        "date_range_start": 50,
        "date_range_end": 70,
        "original_audience": "Jewish Christians",
        "original_language": "greek",
        "literary_features": ["fulfillment formula", "five discourses", "chiasmus", "typology"],
        "reading_context": "Jesus as the promised Messiah and new Moses",
        "canonical_section": "Gospels",
    },
    {
        "book_id": 41,
        "primary_genre": "gospel",
        "secondary_genres": ["narrative", "passion"],
        "author_traditional": "Mark (John Mark)",
        "date_range_start": 55,
        "date_range_end": 70,
        "original_audience": "Roman Christians under persecution",
        "original_language": "greek",
        "literary_features": ["sandwiching", "messianic secret", "irony", "immediacy"],
        "reading_context": "Jesus as the suffering servant and Son of God",
        "canonical_section": "Gospels",
    },
    {
        "book_id": 42,
        "primary_genre": "gospel",
        "secondary_genres": ["narrative", "hymn", "parable"],
        "author_traditional": "Luke",
        "date_range_start": 60,
        "date_range_end": 80,
        "original_audience": "Theophilus and Gentile believers",
        "original_language": "greek",
        "literary_features": ["prologue", "travel narrative", "parables", "hymns", "reversal"],
        "reading_context": "Jesus as Savior of all people, especially the marginalized",
        "canonical_section": "Gospels",
    },
    {
        "book_id": 43,
        "primary_genre": "gospel",
        "secondary_genres": ["theological narrative", "discourse", "signs"],
        "author_traditional": "John (the apostle)",
        "date_range_start": 85,
        "date_range_end": 95,
        "original_audience": "Broader Christian community",
        "original_language": "greek",
        "literary_features": ["signs", "I AM sayings", "irony", "chiasmus", "prologue"],
        "reading_context": "Jesus as the eternal Word, Son of God, giver of life",
        "canonical_section": "Gospels",
    },
    # --- Acts ---
    {
        "book_id": 44,
        "primary_genre": "narrative",
        "secondary_genres": ["history", "sermon", "travel"],
        "author_traditional": "Luke",
        "date_range_start": 62,
        "date_range_end": 85,
        "original_audience": "Theophilus and Gentile believers",
        "original_language": "greek",
        "literary_features": ["speeches", "travel narrative", "parallelism", "summary statements"],
        "reading_context": "Spread of the gospel from Jerusalem to Rome through the Spirit",
        "canonical_section": "Acts",
    },
    # --- Pauline Epistles ---
    {
        "book_id": 45,
        "primary_genre": "epistle",
        "secondary_genres": ["theological treatise", "diatribe"],
        "author_traditional": "Paul",
        "date_range_start": 55,
        "date_range_end": 58,
        "original_audience": "Church in Rome",
        "original_language": "greek",
        "literary_features": ["diatribe", "chiasmus", "catena", "olive tree metaphor"],
        "reading_context": "Systematic presentation of the gospel: sin, grace, faith, and hope",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 46,
        "primary_genre": "epistle",
        "secondary_genres": ["pastoral", "ethical instruction"],
        "author_traditional": "Paul",
        "date_range_start": 53,
        "date_range_end": 55,
        "original_audience": "Church in Corinth",
        "original_language": "greek",
        "literary_features": ["rhetorical questions", "chiasmus", "body metaphor"],
        "reading_context": "Addressing divisions, immorality, and spiritual gifts in the church",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 47,
        "primary_genre": "epistle",
        "secondary_genres": ["apologetic", "personal"],
        "author_traditional": "Paul",
        "date_range_start": 55,
        "date_range_end": 57,
        "original_audience": "Church in Corinth",
        "original_language": "greek",
        "literary_features": ["fool's speech", "catalog of sufferings", "irony"],
        "reading_context": "Paul's defense of his apostleship and theology of weakness",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 48,
        "primary_genre": "epistle",
        "secondary_genres": ["polemical", "theological"],
        "author_traditional": "Paul",
        "date_range_start": 48,
        "date_range_end": 55,
        "original_audience": "Churches in Galatia",
        "original_language": "greek",
        "literary_features": ["autobiography", "allegory", "antithesis"],
        "reading_context": "Freedom in Christ versus legalism; justification by faith",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 49,
        "primary_genre": "epistle",
        "secondary_genres": ["hymnic", "theological"],
        "author_traditional": "Paul",
        "date_range_start": 60,
        "date_range_end": 62,
        "original_audience": "Church in Ephesus",
        "original_language": "greek",
        "literary_features": ["hymn", "household code", "armor metaphor", "prayer"],
        "reading_context": "Unity of the church as Christ's body; spiritual warfare",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 50,
        "primary_genre": "epistle",
        "secondary_genres": ["personal", "ethical"],
        "author_traditional": "Paul",
        "date_range_start": 60,
        "date_range_end": 62,
        "original_audience": "Church in Philippi",
        "original_language": "greek",
        "literary_features": ["Christ hymn", "joy motif", "friendship letter"],
        "reading_context": "Joy and contentment in Christ amid suffering",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 51,
        "primary_genre": "epistle",
        "secondary_genres": ["polemical", "hymnic"],
        "author_traditional": "Paul",
        "date_range_start": 60,
        "date_range_end": 62,
        "original_audience": "Church in Colossae",
        "original_language": "greek",
        "literary_features": ["Christ hymn", "vice/virtue lists", "household code"],
        "reading_context": "Supremacy of Christ over all things; against false teaching",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 52,
        "primary_genre": "epistle",
        "secondary_genres": ["eschatological", "pastoral"],
        "author_traditional": "Paul",
        "date_range_start": 50,
        "date_range_end": 52,
        "original_audience": "Church in Thessalonica",
        "original_language": "greek",
        "literary_features": ["thanksgiving", "eschatological instruction", "paraenesis"],
        "reading_context": "Encouragement and teaching about Christ's return",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 53,
        "primary_genre": "epistle",
        "secondary_genres": ["eschatological", "corrective"],
        "author_traditional": "Paul",
        "date_range_start": 50,
        "date_range_end": 52,
        "original_audience": "Church in Thessalonica",
        "original_language": "greek",
        "literary_features": ["apocalyptic imagery", "man of lawlessness"],
        "reading_context": "Correcting misunderstandings about the day of the Lord",
        "canonical_section": "Pauline Epistles",
    },
    {
        "book_id": 54,
        "primary_genre": "epistle",
        "secondary_genres": ["pastoral", "church order"],
        "author_traditional": "Paul",
        "date_range_start": 62,
        "date_range_end": 65,
        "original_audience": "Timothy in Ephesus",
        "original_language": "greek",
        "literary_features": ["faithful sayings", "vice/virtue lists", "church order"],
        "reading_context": "Instructions for church leadership and sound doctrine",
        "canonical_section": "Pastoral Epistles",
    },
    {
        "book_id": 55,
        "primary_genre": "epistle",
        "secondary_genres": ["personal", "farewell"],
        "author_traditional": "Paul",
        "date_range_start": 66,
        "date_range_end": 67,
        "original_audience": "Timothy",
        "original_language": "greek",
        "literary_features": ["farewell testament", "athletic metaphors"],
        "reading_context": "Paul's final charge to Timothy before his death",
        "canonical_section": "Pastoral Epistles",
    },
    {
        "book_id": 56,
        "primary_genre": "epistle",
        "secondary_genres": ["pastoral", "ethical"],
        "author_traditional": "Paul",
        "date_range_start": 62,
        "date_range_end": 65,
        "original_audience": "Titus on Crete",
        "original_language": "greek",
        "literary_features": ["faithful sayings", "virtue lists", "grace theology"],
        "reading_context": "Church organization and godly living in Crete",
        "canonical_section": "Pastoral Epistles",
    },
    {
        "book_id": 57,
        "primary_genre": "epistle",
        "secondary_genres": ["personal", "appeal"],
        "author_traditional": "Paul",
        "date_range_start": 60,
        "date_range_end": 62,
        "original_audience": "Philemon in Colossae",
        "original_language": "greek",
        "literary_features": ["wordplay", "persuasion", "chiasmus"],
        "reading_context": "Appeal for reconciliation between master and slave in Christ",
        "canonical_section": "Pauline Epistles",
    },
    # --- General Epistles ---
    {
        "book_id": 58,
        "primary_genre": "epistle",
        "secondary_genres": ["sermon", "theological treatise"],
        "author_traditional": "Unknown (Paul, Apollos, or Barnabas)",
        "date_range_start": 60,
        "date_range_end": 70,
        "original_audience": "Jewish Christians considering returning to Judaism",
        "original_language": "greek",
        "literary_features": ["typology", "chiasmus", "comparison", "warning passages"],
        "reading_context": "Superiority of Christ and the new covenant over the old",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 59,
        "primary_genre": "epistle",
        "secondary_genres": ["wisdom", "ethical instruction"],
        "author_traditional": "James (brother of Jesus)",
        "date_range_start": 45,
        "date_range_end": 50,
        "original_audience": "Jewish Christians in the diaspora",
        "original_language": "greek",
        "literary_features": ["diatribe", "wisdom sayings", "imperatives"],
        "reading_context": "Practical faith demonstrated through works and speech",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 60,
        "primary_genre": "epistle",
        "secondary_genres": ["pastoral", "exhortation"],
        "author_traditional": "Peter",
        "date_range_start": 60,
        "date_range_end": 65,
        "original_audience": "Christians in Asia Minor facing persecution",
        "original_language": "greek",
        "literary_features": ["household code", "stone imagery", "suffering motif"],
        "reading_context": "Hope and holiness amid suffering and persecution",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 61,
        "primary_genre": "epistle",
        "secondary_genres": ["apologetic", "eschatological"],
        "author_traditional": "Peter",
        "date_range_start": 65,
        "date_range_end": 68,
        "original_audience": "Same audience as 1 Peter",
        "original_language": "greek",
        "literary_features": ["farewell testament", "virtue ladder", "cosmic imagery"],
        "reading_context": "Warning against false teachers and the certainty of Christ's return",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 62,
        "primary_genre": "epistle",
        "secondary_genres": ["theological", "ethical"],
        "author_traditional": "John (the apostle)",
        "date_range_start": 85,
        "date_range_end": 95,
        "original_audience": "Johannine community",
        "original_language": "greek",
        "literary_features": ["antithesis", "spiral argument", "light/darkness motif"],
        "reading_context": "Assurance of faith through love, truth, and obedience",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 63,
        "primary_genre": "epistle",
        "secondary_genres": ["personal"],
        "author_traditional": "John (the apostle)",
        "date_range_start": 85,
        "date_range_end": 95,
        "original_audience": "The elect lady (a church)",
        "original_language": "greek",
        "literary_features": ["brevity", "truth and love emphasis"],
        "reading_context": "Walking in truth and guarding against false teachers",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 64,
        "primary_genre": "epistle",
        "secondary_genres": ["personal", "commendation"],
        "author_traditional": "John (the apostle)",
        "date_range_start": 85,
        "date_range_end": 95,
        "original_audience": "Gaius",
        "original_language": "greek",
        "literary_features": ["character contrast", "hospitality theme"],
        "reading_context": "Commendation of hospitality and warning against Diotrephes",
        "canonical_section": "General Epistles",
    },
    {
        "book_id": 65,
        "primary_genre": "epistle",
        "secondary_genres": ["polemical", "apocalyptic"],
        "author_traditional": "Jude (brother of Jesus)",
        "date_range_start": 65,
        "date_range_end": 80,
        "original_audience": "General Christian audience",
        "original_language": "greek",
        "literary_features": ["triplets", "OT allusions", "doxology"],
        "reading_context": "Contending for the faith against false teachers",
        "canonical_section": "General Epistles",
    },
    # --- Revelation ---
    {
        "book_id": 66,
        "primary_genre": "apocalyptic",
        "secondary_genres": ["prophecy", "epistle", "vision"],
        "author_traditional": "John (the apostle)",
        "date_range_start": 90,
        "date_range_end": 96,
        "original_audience": "Seven churches in Asia Minor",
        "original_language": "greek",
        "literary_features": ["symbolic numbers", "hymns", "chiasmus", "OT allusions", "throne room"],
        "reading_context": "God's ultimate victory over evil and the new creation",
        "canonical_section": "Revelation",
    },
]


class BookMetadataPopulator:
    """Populates the book_metadata table with curated data for all 66 books."""

    def __init__(self, db_path: Path) -> None:
        self.db_path = db_path

    def populate(self, force: bool = False) -> int:
        """Insert book metadata into the database.

        Args:
            force: If True, replace existing rows.

        Returns:
            Number of rows inserted or replaced.
        """
        inserted = 0
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()

            # Ensure table exists
            cursor.execute("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='book_metadata'")
            if cursor.fetchone()[0] == 0:
                logger.warning("book_metadata table does not exist; run migrations first")
                return 0

            for meta in BOOK_METADATA:
                try:
                    if force:
                        sql = (
                            "INSERT OR REPLACE INTO book_metadata "
                            "(book_id, primary_genre, secondary_genres, author_traditional, "
                            "date_range_start, date_range_end, original_audience, original_language, "
                            "literary_features, reading_context, canonical_section) "
                            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                        )
                    else:
                        sql = (
                            "INSERT OR IGNORE INTO book_metadata "
                            "(book_id, primary_genre, secondary_genres, author_traditional, "
                            "date_range_start, date_range_end, original_audience, original_language, "
                            "literary_features, reading_context, canonical_section) "
                            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                        )

                    cursor.execute(
                        sql,
                        (
                            meta["book_id"],
                            meta["primary_genre"],
                            json.dumps(meta.get("secondary_genres", [])),
                            meta.get("author_traditional"),
                            meta.get("date_range_start"),
                            meta.get("date_range_end"),
                            meta.get("original_audience"),
                            meta.get("original_language"),
                            json.dumps(meta.get("literary_features", [])),
                            meta.get("reading_context"),
                            meta.get("canonical_section"),
                        ),
                    )
                    if cursor.rowcount > 0:
                        inserted += 1
                except sqlite3.Error as e:
                    logger.error("Failed to insert book_id=%d: %s", meta["book_id"], e)

            conn.commit()

        logger.info("Populated book_metadata: %d rows inserted", inserted)
        return inserted

    @staticmethod
    def get_metadata_for_book(book_id: int) -> Optional[Dict[str, Any]]:
        """Get metadata dict for a specific book from the constant data."""
        for meta in BOOK_METADATA:
            if meta["book_id"] == book_id:
                return meta
        return None
